### ISSUE TITLE
Any way to secure the AZURE_CLIENT_KEY in aci-connector.yaml?

### ISSUE THREAD

**Issue by ddebroy** [Azure/aci-connector-k8s#11]
The `AZURE_CLIENT_KEY` key parameter that needs to be stored in aci-connector.yaml is a secret. But it appears to be stored in plain text in the yaml file which does not seem secure. Is there any guidance on how this may be secured?

The `az` command line suggested in the README creates a SP with subscription-wide scope with `contributor` role. Users following the steps are going to store the corresponding SP's credentials in plain text. This makes the situation especially dangerous as someone who can get access to the yaml file can abuse the whole subscription using the rather highly privileged SP credential details in plain text. Perhaps the SP creation command line can be scoped to only the resource groups where the containers will be scheduled and the role scoped to only ACI container creation?

**Comment by koalalorenzo** [comment]
You should be able to use a Secret in kubernetes.
Try something like:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-credentials
type: Opaque
data:
  AZURE_CLIENT_ID: BASE64_VALUE
  AZURE_CLIENT_KEY: BASE64_VALUE
  AZURE_TENANT_ID: BASE64_VALUE 
  AZURE_SUBSCRIPTION_ID: BASE64_VALUE 
  ACI_RESOURCE_GROUP: BASE64_VALUE
---
```

And then for each variable you add the source from the secret:
```
      - name: ACI_RESOURCE_GROUP
        valueFrom:
          secretKeyRef:
            name: aci-credentials
            key: ACI_RESOURCE_GROUP
```

This is an example I am testing right now!
