### ISSUE TITLE
k8s keeps creating pods when targeting ACI (Image hosted on ACR)

### ISSUE THREAD

**Issue by ThorstenHans** [Azure/aci-connector-k8s#32]
When using an deployment like this

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: some-api
    spec:
      containers:
        - name: some-api
          image: myacr.azurecr.io/some-api
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-config
      dnsPolicy: ClusterFirst
      nodeName: aci-connector
```

k8s keeps endlessly spinning up new pods. Each pod is providing the same log
`Error from server: no preferred addresses found; known addresses: []`

When I use an image from docker hub everything works as expected. Looks like the `imagePullSecrets` is ignored when targeting ACI. It also works if I target a regular node in my cluster. 

Unfortunately the logs aren't that good on k8s side. ACR came into my mind due to the Azure Portal. A couple of seconds after a pod gots created, it appears in the Azure Portal with Status `Waiting`

![image](https://user-images.githubusercontent.com/357884/29652008-cc68ef2a-88a3-11e7-8e40-770a02c5ff8c.png)
